language: php

php:
    - 7.0
    - 7.1
    - 7.2

sudo: false

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer self-update

install: composer update

script:
    - phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash)
